---
-name: install apache2 on Debian machines
 hosts: web
 become: yes
 tasks:
        - name: install Apache2
          apt
                name: apache2
                state: present
          when ansible_distribution == 'ubuntu'

- name: install httpd on CentOS machines
  hosts: web
  become: yes
  tasks:
        - name: install httpd on centOs
          yum:
                name: httpd
                state: present
          when ansible_distribution == 'CentOs'
